swagger: "2.0"
info:
  title: BlockChain parser
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
paths:
  /block/number:
    get:
      tags:
        - block
      responses:
        200:
          description: Return last parsed block number
          schema:
            type: object
            required:
              - block
            properties:
              block:
                type: integer
                description: Last parsed block number
        422:
          description: Fail to process request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/Error"

  /address/subscribe:
    post:
      tags:
        - address
      parameters:
        - in: body
          name: body
          description: Subscribe body
          schema:
            type: object
            required:
              - address
            properties:
              address:
                type: string
                format: hex
                description: Address for tracking transactions.
      responses:
        204:
          description: Successful subscription
        422:
          description: Fail to process request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/Error"

  /address/transaction:
    get:
      tags:
        - address
      parameters:
        - in: query
          name: address
          description: Address to get transactions
          type: string
      responses:
        200:
          description: Transactions list
          schema:
            type: object
            required:
              - transactions
            properties:
              transactions:
                type: array
                items:
                  type: object
                  required:
                    - from
                    - to
                    - value
                  properties:
                    from:
                      type: string
                      description: Output address
                    to:
                      type: string
                      description: Input address
                    value:
                      type: string
                      description: Value transferred in Wei
        422:
          description: Fail to process request
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/Error"

definitions:
  Error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        description: Short message description
        example: object not found
